server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.64.135:3306/mp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false

